- name: dconf_update
  command: dconf update
- name: auditd_restart
  service:
    name: auditd
    state: restarted
    use: service
- name: ssh_restart
  service:
    name: sshd
    state: restarted
